### ISSUE TITLE
upgrading using brew throws "Error: Calling Formula.sha1 is disabled!"

### ISSUE THREAD

**Issue by dimvic** [brona/iproute2mac#12]
Related issue describing why this should not be considered a homebrew problem:
https://github.com/Homebrew/homebrew-core/issues/6999

```
dimitris ~ $ brew upgrade iproute2mac
Updating Homebrew...
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/brona/homebrew-iproute2mac/iproute2mac.rb:6:in `<class:Iproute2mac>'
Please report this to the brona/iproute2mac tap!
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils.rb:86:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/utils.rb:94:in `odisabled'
/usr/local/Homebrew/Library/Homebrew/compat/sha1.rb:3:in `sha1'
/usr/local/Homebrew/Library/Taps/brona/homebrew-iproute2mac/iproute2mac.rb:6:in `<class:Iproute2mac>'
/usr/local/Homebrew/Library/Taps/brona/homebrew-iproute2mac/iproute2mac.rb:3:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:201:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:241:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:272:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:255:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:68:in `block in resolved_formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:52:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:52:in `resolved_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:43:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by brona** [comment]
iproute2mac already merged to homebrew-core, my tap is no longer supported. However I copied formula from homebrew-core so it should no longer be issue.
