### ISSUE TITLE
ip n s dev <interface> doesn't work

### ISSUE THREAD

**Issue by SimonTate** [brona/iproute2mac#43]
With brew installed iprotue2:

When trying to execute `ip n s dev en7`, I get a python error.

```
$ ip n s dev en7
Traceback (most recent call last):
  File "/usr/local/bin/ip", line 762, in <module>
    main(sys.argv[1:])
  File "/usr/local/bin/ip", line 92, in inner
    if not func(*args, **kwargs):
  File "/usr/local/bin/ip", line 755, in main
    return cmd_func(argv, af)
  File "/usr/local/bin/ip", line 92, in inner
    if not func(*args, **kwargs):
  File "/usr/local/bin/ip", line 599, in do_neigh
    return do_neigh_show(argv, af)
  File "/usr/local/bin/ip", line 657, in do_neigh_show
    res = subprocess.run(
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/sbin/arp', '-anli en7']' returned non-zero exit status 1.
```

Also get the same on master of the repo.

I have a change ready for this.

**Comment by brona** [comment]
Thanks for the fix. Released in v1.4.1
