### ISSUE TITLE
ip addr fails to list the devices with the associated information and throws an exception

### ISSUE THREAD

**Issue by msubietab** [brona/iproute2mac#57]
In the past versions (two or three ago, cannot really tell when this issue started), when issuing the ip addr command at the prompt I would get a list of all the adapters on my mac with their ip address and associated information. Currently when issuing the same command, I get the following error (in more than one mac, btw):

└» ip addr
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/iproute2mac/1.5.1/libexec/ip", line 713, in <module>
    main(sys.argv[1:])
  File "/opt/homebrew/Cellar/iproute2mac/1.5.1/libexec/iproute2mac.py", line 96, in inner
    if not func(*args, **kwargs):
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/iproute2mac/1.5.1/libexec/ip", line 706, in main
    return cmd_func(argv, af, json_print, pretty_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/iproute2mac/1.5.1/libexec/iproute2mac.py", line 96, in inner
    if not func(*args, **kwargs):
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/iproute2mac/1.5.1/libexec/ip", line 394, in do_addr
    return do_addr_show(argv, af, json_print, pretty_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/iproute2mac/1.5.1/libexec/ip", line 407, in do_addr_show
    return link_addr_show(argv, af, json_print, pretty_json, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/iproute2mac/1.5.1/libexec/ip", line 106, in link_addr_show
    links = parse_ifconfig(res, af, address)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/iproute2mac/1.5.1/libexec/ip", line 31, in parse_ifconfig
    (ifname, flags, mtu, ifindex) = re.findall(
                                    ^^^^^^^^^^^
IndexError: list index out of range

**Comment by brona** [comment]
Thank you, the problematic line was:
`feth4174: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 5000 mtu 2800 index 19`

I am reasling v1.5.2 with the fix.

**Comment by brona** [comment]
https://github.com/Homebrew/homebrew-core/pull/180419 in progress, fixed in HEAD.

@signal-09 FYI
